# Generated by Django 3.2.13 on 2022-07-21 15:21

import BlogApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_alter_post_postimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.FileField(null=True, upload_to=BlogApp.models.Post.user_directory_path),
        ),
    ]
