# Generated by Django 3.2.13 on 2022-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_auto_20220725_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='preference',
            name='vote',
            field=models.IntegerField(choices=[(0, 'Like'), (1, 'Dislike')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('user', 'post', 'vote')},
        ),
        migrations.RemoveField(
            model_name='preference',
            name='value',
        ),
    ]
