# Generated by Django 3.2.13 on 2022-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_auto_20220726_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='vote',
            field=models.IntegerField(choices=[(0, 'Like'), (1, 'Dislike')], default='', null=True),
        ),
    ]
