# Generated by Django 3.2.13 on 2022-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_alter_like_dislike_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_dislike',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
