# Generated by Django 3.2.13 on 2022-07-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0017_auto_20220727_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
    ]
