# Generated by Django 3.2.13 on 2022-07-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_remove_userprofile_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
