# Generated by Django 3.2.13 on 2022-07-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0019_delete_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
