# Generated by Django 3.2.13 on 2022-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0023_auto_20220801_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_dislike',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Like'), (0, 'Dislike')], default='', null=True),
        ),
    ]
